#!/usr/bin/env python3
"""Inspect a TopK project: verify credentials, list collections, describe one.

Usage:
  python scripts/topk_inspect.py check
  python scripts/topk_inspect.py describe <collection> [--partition <name>] [--sample N]

Reads TOPK_API_KEY and TOPK_REGION from the environment. Requires `pip install topk-sdk`.
Prints JSON so the output is easy to parse. Never prints the API key.
"""
import argparse
import json
import os
import sys

REGIONS = ["aws-us-east-1-elastica", "aws-eu-central-1-monstera", "gcp-us-east4-aloe"]


def fail(message: str, code: int = 1) -> None:
    print(json.dumps({"ok": False, "error": message}, indent=2))
    sys.exit(code)


def client():
    try:
        from topk_sdk import Client
    except ImportError:
        fail("topk-sdk is not installed. Run: pip install topk-sdk")
    api_key = os.environ.get("TOPK_API_KEY")
    region = os.environ.get("TOPK_REGION")
    if not api_key:
        fail("TOPK_API_KEY is not set. Create a key at https://console.topk.io/api-key")
    if not region:
        fail(f"TOPK_REGION is not set. Use one of: {', '.join(REGIONS)}")
    return Client(api_key=api_key, region=region), region


def field_summary(spec) -> str:
    # FieldSpec repr looks like: FieldSpec { data_type: Text, required: true, index: Some(SemanticIndex) }
    return str(spec).replace("FieldSpec ", "")


def preview(doc: dict, max_chars: int = 200) -> dict:
    # Hide internal fields (e.g. `_embedding_smve.<field>`, generated by semantic_index) and shorten long text.
    out = {}
    for k, v in doc.items():
        if k.startswith("_embedding"):
            continue
        if isinstance(v, str) and len(v) > max_chars:
            v = v[:max_chars] + f"... ({len(v)} chars)"
        out[k] = v
    return out


def check(_args) -> None:
    from topk_sdk.error import PermissionDeniedError

    c, region = client()
    try:
        collections = c.collections().list()
    except PermissionDeniedError:
        fail("Permission denied: TOPK_API_KEY is invalid, revoked, or for a different project.")
    except Exception as e:  # bad key (Unauthenticated), network, or region problems
        if "Unauthenticated" in str(e):
            fail("TOPK_API_KEY was rejected (Unauthenticated). Check the key at https://console.topk.io/api-key")
        fail(f"Could not reach TopK in region {region!r}: {type(e).__name__}: {e}")
    print(json.dumps({
        "ok": True,
        "region": region,
        "collections": sorted(col.name for col in collections),
    }, indent=2))


def describe(args) -> None:
    from topk_sdk.error import CollectionNotFoundError, PartitionNotFoundError
    from topk_sdk.query import field, select

    c, region = client()
    try:
        col = c.collections().get(args.collection)
    except CollectionNotFoundError:
        names = sorted(x.name for x in c.collections().list())
        fail(f"Collection {args.collection!r} not found in {region}. Existing: {names}")

    data = c.collection(args.collection, args.partition)
    out = {
        "ok": True,
        "collection": col.name,
        "region": region,
        "partition": args.partition,
        "schema": {name: field_summary(spec) for name, spec in col.schema.items()},
    }
    try:
        out["count"] = data.count()
        # Sorting by _id gives a stable sample without needing any index; get() returns all fields.
        ids = [d["_id"] for d in data.query(select().sort(field("_id"), asc=True).limit(args.sample))]
        docs = data.get(ids) if ids else {}
        out["sample"] = [preview(docs[i]) for i in ids if i in docs]
    except PartitionNotFoundError:
        out["count"] = 0
        out["sample"] = []
        out["note"] = f"Partition {args.partition!r} has no data (never written, or deleted)."
    if args.partition is None:
        try:
            out["partitions"] = [p.name for p in c.collection(args.collection).list_partitions()]
        except Exception:
            pass
    print(json.dumps(out, indent=2, default=str))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("check", help="verify credentials and list collections").set_defaults(func=check)
    d = sub.add_parser("describe", help="show schema, count and sample documents")
    d.add_argument("collection")
    d.add_argument("--partition", default=None)
    d.add_argument("--sample", type=int, default=3, help="number of sample documents (default 3)")
    d.set_defaults(func=describe)
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
