[package]
name = "topk-cli"
version = "0.15.0"
edition = "2021"
description = "TopK CLI"
license = "MIT"
repository = "https://github.com/topk-io/topk"
homepage = "https://topk.io"

[lib]
name = "topk"
path = "src/lib.rs"

[[bin]]
name = "topk"
path = "src/main.rs"

[dependencies]
topk-rs = { path = "../topk-rs", features = ["json"] }
duckdb = { version = "1", features = ["bundled", "parquet"] }
elasticsearch = { version = "8.15.0-alpha.1" }
mongodb = { version = "3" }
async-stream = { version = "0.3" }
float8 = { version = "0.5" }
half = { version = "2" }
indexmap = { version = "2", features = ["serde"] }
prost = { version = "0.14" }
strum = { version = "0.26", features = ["derive"] }
thiserror = { version = "1" }
topk-es = { path = "../topk-es" }
url = { version = "2" }
wildmatch = { version = "2" }
clap = { version = "4", features = ["derive", "env"] }
clap_complete = { version = "4" }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1" }
anyhow = { version = "1" }
async-trait = "0.1"
serde_json = { version = "1" }
indicatif = { version = "0.17" }
tracing = { version = "0.1" }
regex = { version = "1" }
futures = { version = "0.3" }
serde = { version = "1", features = ["derive"] }
base64 = "0.22"
bytes = "1"
bytesize = { version = "1", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
comfy-table = { version = "7" }
terminal_size = "0.4"
glob = "0.3"
shellexpand = "3"
sha2 = "0.10"
dirs = "5"
open = "5"
toml = { version = "0.8", features = ["preserve_order"] }
dialoguer = "0.11"
colored = "2"
tempfile = "3"
humantime = "2"

[dev-dependencies]
assert_cmd = "2"
rstest = "0.23"
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "postgres",
    "mysql",
    "sqlite",
] }
test-macros = { path = "../utils/test-macros" }
test-context = { version = "0.3" }
uuid = { version = "1", features = ["v4"] }
tokio = { version = "1", features = ["full"] }
