syntax = "proto3";
package topk.management.v1;

service ProjectService {
  rpc ListProjects(ListProjectsRequest) returns (ListProjectsResponse);
  rpc GetProject(GetProjectRequest) returns (GetProjectResponse);
  rpc CreateProject(CreateProjectRequest) returns (CreateProjectResponse);
  rpc DeleteProject(DeleteProjectRequest) returns (DeleteProjectResponse);
}

message Project {
  string org_id = 1;
  string project_id = 2;
  string name = 3;
  int64 created_at = 4;
}

message ListProjectsRequest {
}
message ListProjectsResponse {
  repeated Project projects = 1;
}

message GetProjectRequest {
  string project_id = 1;
}
message GetProjectResponse {
  Project project = 1;
}

message CreateProjectRequest {
  string name = 1;
}
message CreateProjectResponse {
  Project project = 1;
}

message DeleteProjectRequest {
  string project_id = 1;
}
message DeleteProjectResponse {}
