/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'topk-js.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./topk-js.android-arm64.node')
          } else {
            nativeBinding = require('topk-js-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'topk-js.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./topk-js.android-arm-eabi.node')
          } else {
            nativeBinding = require('topk-js-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'topk-js.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./topk-js.win32-x64-msvc.node')
          } else {
            nativeBinding = require('topk-js-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'topk-js.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./topk-js.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('topk-js-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'topk-js.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./topk-js.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('topk-js-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'topk-js.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./topk-js.darwin-universal.node')
      } else {
        nativeBinding = require('topk-js-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'topk-js.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./topk-js.darwin-x64.node')
          } else {
            nativeBinding = require('topk-js-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'topk-js.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./topk-js.darwin-arm64.node')
          } else {
            nativeBinding = require('topk-js-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'topk-js.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./topk-js.freebsd-x64.node')
      } else {
        nativeBinding = require('topk-js-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'topk-js.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./topk-js.linux-x64-musl.node')
            } else {
              nativeBinding = require('topk-js-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'topk-js.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./topk-js.linux-x64-gnu.node')
            } else {
              nativeBinding = require('topk-js-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'topk-js.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./topk-js.linux-arm64-musl.node')
            } else {
              nativeBinding = require('topk-js-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'topk-js.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./topk-js.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('topk-js-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'topk-js.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./topk-js.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('topk-js-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'topk-js.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./topk-js.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('topk-js-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'topk-js.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./topk-js.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('topk-js-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'topk-js.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./topk-js.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('topk-js-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'topk-js.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./topk-js.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('topk-js-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { CollectionsClient, CollectionClient, DataType, FieldIndex, KeywordIndexType, VectorDistanceMetric, EmbeddingDataType, FieldSpec, BinaryOperator, VectorQuery, FunctionExpression, semanticSimilarity, vectorDistance, bm25Score, LogicalExpressionUnion, LogicalExpression, Query, field, match, select, Stage, TextExpressionUnion, TextExpression, UnaryOperator, Client } = nativeBinding

module.exports.CollectionsClient = CollectionsClient
module.exports.CollectionClient = CollectionClient
module.exports.DataType = DataType
module.exports.FieldIndex = FieldIndex
module.exports.KeywordIndexType = KeywordIndexType
module.exports.VectorDistanceMetric = VectorDistanceMetric
module.exports.EmbeddingDataType = EmbeddingDataType
module.exports.FieldSpec = FieldSpec
module.exports.BinaryOperator = BinaryOperator
module.exports.VectorQuery = VectorQuery
module.exports.FunctionExpression = FunctionExpression
module.exports.semanticSimilarity = semanticSimilarity
module.exports.vectorDistance = vectorDistance
module.exports.bm25Score = bm25Score
module.exports.LogicalExpressionUnion = LogicalExpressionUnion
module.exports.LogicalExpression = LogicalExpression
module.exports.Query = Query
module.exports.field = field
module.exports.match = match
module.exports.select = select
module.exports.Stage = Stage
module.exports.TextExpressionUnion = TextExpressionUnion
module.exports.TextExpression = TextExpression
module.exports.UnaryOperator = UnaryOperator
module.exports.Client = Client
