name: CI

on:
  workflow_call:
    inputs:
      tests:
        type: boolean
        description: "Run tests"
        default: true

jobs:
  rust:
    name: Test Rust
    runs-on: public-amd64
    if: ${{ inputs.tests }}
    env:
      FORCE_COLOR: 1
      EARTHLY_DISABLE_ANALYTICS: 1
      EARTHLY_DISABLE_LOG_SHARING: 1
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install earthly
        run: |
          sudo bash -c "curl -L https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -o /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly"

      - name: Rust tests
        run: earthly --secret TOPK_API_KEY +test-rs --region sunflower --host=topk.dev
        env:
          TOPK_API_KEY: ${{ secrets.TOPK_API_KEY }}

  python:
    name: Test Python
    runs-on: public-amd64
    if: ${{ inputs.tests }}
    env:
      FORCE_COLOR: 1
      EARTHLY_DISABLE_ANALYTICS: 1
      EARTHLY_DISABLE_LOG_SHARING: 1
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install earthly
        run: |
          sudo bash -c "curl -L https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -o /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly"

      - name: Python tests
        run: earthly --secret TOPK_API_KEY +test-py --region sunflower --host=topk.dev
        env:
          TOPK_API_KEY: ${{ secrets.TOPK_API_KEY }}

  javascript:
    name: Test JavaScript
    runs-on: public-amd64
    if: ${{ inputs.tests }}
    env:
      FORCE_COLOR: 1
      EARTHLY_DISABLE_ANALYTICS: 1
      EARTHLY_DISABLE_LOG_SHARING: 1
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install earthly
        run: |
          sudo bash -c "curl -L https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -o /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly"

      - name: JavaScript tests
        run: earthly --secret TOPK_API_KEY +test-js --region sunflower --host=topk.dev
        env:
          TOPK_API_KEY: ${{ secrets.TOPK_API_KEY }}

  cli:
    name: Test CLI
    runs-on: public-amd64
    if: ${{ inputs.tests }}
    env:
      FORCE_COLOR: 1
      EARTHLY_DISABLE_ANALYTICS: 1
      EARTHLY_DISABLE_LOG_SHARING: 1
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install earthly
        run: |
          sudo bash -c "curl -L https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -o /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly"

      - name: CLI tests
        run: earthly --secret TOPK_API_KEY +test-cli --region sunflower --host=topk.dev
        env:
          TOPK_API_KEY: ${{ secrets.TOPK_API_KEY }}

  sql:
    name: Test SQL
    runs-on: public-amd64
    if: ${{ inputs.tests }}
    env:
      FORCE_COLOR: 1
      EARTHLY_DISABLE_ANALYTICS: 1
      EARTHLY_DISABLE_LOG_SHARING: 1
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install earthly
        run: |
          sudo bash -c "curl -L https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -o /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly"

      - name: SQL tests
        run: earthly --secret TOPK_API_KEY +test-sql --region sunflower --host=topk.dev
        env:
          TOPK_API_KEY: ${{ secrets.TOPK_API_KEY }}

  all_sdks_same_version:
    name: Verify all SDKs on the same version
    runs-on: public-amd64
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Install bun dependencies
        run: bun add commander

      - name: Check all SDKs versions
        run: |
          bun run utils/bump-release-version.ts check

  all_sdks_sdk_reference_docs_sync:
    name: Verify SDKs reference docs are in sync
    if: true
    runs-on: public-amd64
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          cache: "yarn"
          cache-dependency-path: |
            **/yarn.lock

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Install dependencies
        run: yarn install
        working-directory: ./topk-js

      - name: Install bun dependencies
        run: bun add commander

      - name: Check all SDKs reference docs are in sync
        run: |
          bun run utils/verify-sdk-docs-sync.ts check

  pre_commit:
    name: Verify pre-commit hooks pass
    runs-on: public-amd64
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0

      - name: Run pre-commit
        run: uvx pre-commit run --all-files --show-diff-on-failure --color always

  pinact:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: suzuki-shunsuke/pinact-action@cf51507d80d4d6522a07348e3d58790290eaf0b6 # v2.0.0
        with:
          skip_push: true
