name: Auto Approve Self PRs

on:
  pull_request:
    types: [opened, synchronize, labeled, reopened]

jobs:
  self-approve:
    if: github.actor == github.event.pull_request.user.login && contains(github.event.pull_request.labels.*.name, 'self-approve')
    runs-on: ubuntu-latest
    steps:
      - uses: topk-io/platform/.github/actions/create-github-app-token@main
        id: app-token
        with:
          app-id: ${{ secrets.GH_SELF_APPROVE_APP_ID }}
          private-key: ${{ secrets.GH_SELF_APPROVE_PRIVATE_KEY }}

      - name: Auto approve
        uses: topk-io/platform/.github/actions/auto-approve@main
        with:
          github-token: ${{ steps.app-token.outputs.token }}
